# Generated by Django 4.2.1 on 2023-07-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0002_alter_salida_producto_fechasalida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devolucion_producto',
            old_name='descripcionSalida',
            new_name='descripcionDevolucion',
        ),
        migrations.AlterField(
            model_name='devolucion_producto',
            name='fechaDevolucion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='entrada_producto',
            name='fechaEntrada',
            field=models.DateTimeField(),
        ),
    ]
