# Generated by Django 4.2.1 on 2023-07-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0003_rename_descripcionsalida_devolucion_producto_descripciondevolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion_producto',
            name='fechaDevolucion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='entrada_producto',
            name='fechaEntrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salida_producto',
            name='fechaSalida',
            field=models.DateField(),
        ),
    ]
