# Generated by Django 3.2.19 on 2023-07-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0005_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
